config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check
  root to: "produtos#index"
  resources :produtos
  get "busca", to: "produtos#busca"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @produtos = Produto.order :nome
    @produto_com_desconto = Produto.order(:preco).limit 1
  end

  def create
    produto = params.require(:produto).permit(:nome, :descricao, :preco, :quantidade)
    Produto.create produto
    redirect_to root_url
  end

  def destroy
    id = params[:id]
    Produto.destroy id
    redirect_to root_url
  end

  def busca
    pesquisa = params[:nome]
    @resultado = Produto.where("nome LIKE ?", "%#{pesquisa}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= nav_bar brand: "Loja do Auri", brand_link: root_url do %>
    <%= menu_group do %>
      <% menu_item "Criar novo produto", new_produto_path %>
    <% end %>
      <%= form_tag busca_path, method: :get, class:"navbar-form navbar-right" do %>
        <div class="form-group">
          <%= search_field_tag :busca, params[:busca], placeholder: "Digite o produto... ", class:"form-control" %>
          <%= button_tag "Buscar", class:"btn btn-default" %>
        </div>
      <% end %>
  <% end %>
 
  <head>
    <title>Lojinha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <div class="container">
    <body>
      <%= yield %>
    </body>
  </div>

</html>

app/views/produtos/busca.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Preço</td>
      <td>Quantidade</td>
    </tr>
  </thead>
  <tbody>
    <% @resultado.each do |produto| %>
    <tr>
      <td><%= produto.nome %></td>
      <td><%= produto.descricao %></td>
      <td><%= produto.preco %></td>
      <td><%= produto.quantidade %></td>
      <td><%= button_to "Remover", produto, method: :delete, class:"btn btn-danger", data: { turbo_confirm: "Tem certeza que deseja remover o produto #{produto.nome}?" } %></td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/produtos/index.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Preço</td>
      <td>Quantidade</td>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
    <tr>
      <td><%= produto.nome %></td>
      <td><%= produto.descricao %></td>
      <td><%= produto.preco %></td>
      <td><%= produto.quantidade %></td>
      <td><%= button_to "Remover", produto, method: :delete, class:"btn btn-danger", data: { turbo_confirm: "Tem certeza que deseja remover o produto #{produto.nome}?" } %></td>
    </tr>
    <% end %>

  </tbody>
</table>

<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Produto com desconto</h4>
</div>
<table class="table table-bordered table-hover">
    <thead>
    <tr>
      <td>Nome</td>
      <td>Descrição</td>
      <td>Preço</td>
      <td>Quantidade</td>
    </tr>
    </thead>
    <tbody>
    <% @produto_com_desconto.each do |p| %>
    <tr>
      <td><%= p.nome %></td>
      <td><%= p.descricao %></td>
      <td><%= p.preco %></td>
      <td><%= p.quantidade %></td>
    </tr>
    <% end %>
</table>

app/views/produtos/new.html.erb
<%= form_for Produto.new do |form| %>

  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :nome %>
        <%= form.text_field :nome, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :descricao %>
        <%= form.text_area :descricao, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :preco %>
        <%= form.number_field :preco, step:0.01, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
      <div class="form-group">
        <%= form.label :quantidade %>
        <%= form.number_field :quantidade, class:"form-control" %>
      </div>
    </div>
  </div>

  <%= form.submit "Criar", class:"btn btn-primary" %>

<% end %>